# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class UiGetToken(object):
    # 验证码窗口用于人工识别验证码实现模拟登陆
    # The verification code window is used to manually identify the
    # verification code to achieve simulated login
    def setupUi(self, yanzheng):
        yanzheng.setObjectName("yanzheng")
        yanzheng.resize(400, 232)
        self.buttonBox = QtWidgets.QDialogButtonBox(yanzheng)
        self.buttonBox.setGeometry(QtCore.QRect(190, 200, 201, 28))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(yanzheng)
        self.label.setGeometry(QtCore.QRect(20, 20, 251, 16))
        self.label.setObjectName("label")
        self.pic = QtWidgets.QLabel(yanzheng)
        self.pic.setGeometry(QtCore.QRect(30, 60, 341, 121))
        self.pic.setText("")
        self.pic.setObjectName("pic")
        self.pic_value_box = QtWidgets.QLineEdit(yanzheng)
        self.pic_value_box.setGeometry(QtCore.QRect(10, 190, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pic_value_box.setFont(font)
        self.pic_value_box.setObjectName("pic_value_box")
        self.pushButton = QtWidgets.QPushButton(yanzheng)
        self.pushButton.setGeometry(QtCore.QRect(230, 10, 141, 28))
        self.pushButton.setObjectName("pushButton")
        self.retranslateUi(yanzheng)
        QtCore.QMetaObject.connectSlotsByName(yanzheng)

    def retranslateUi(self, yanzheng):
        _translate = QtCore.QCoreApplication.translate
        yanzheng.setWindowTitle(_translate("yanzheng", "验证码窗口"))
        self.label.setText(_translate("yanzheng", "输入验证码以获取token"))
        self.pushButton.setText(_translate("yanzheng", "看不清？换一张"))
